name:                 EDB-Pro
main:                 EDB\EDB
api:                  [3.0.0, 3.0.0-ALPHA10]
version:              Nether
author:               KaitoDoDo

commands:
    edlb:
        usage:        /edlb <make>
        description:  CreateGame
    edlbstart:
        usage:        /edlbstart
        description:  StartGame
