name:                 EDB-Pro
main:                 EDB\EDB
api:                  [3.0.0, 3.0.0-ALPHA10]
version:              0.0.1
authors:              [KaitoDoDo, UlisesGamer, PresentKim]

commands:
    edb:
        usage:        /edb <make>
        description:  CreateGame
    edbstart:
        usage:        /edbstart
        description:  StartGame
