name: EDLBDoDo
main: EDLB\EDLB
api: [1.0.0, 2.0.0]
version: Nether
author: KaitoDoDo

commands:
    edlb:
        usage: /edlb <make>
        description: CreateGame
    edlbstart:
        usage: /edlbstart
        description: StartGame