name:                 RunnersAndBeast
main:                 presentkim\rab\RunnersAndBeast
api:                  [3.0.0, 3.0.0-ALPHA10]
version:              0.0.1
authors:              [KaitoDoDo, UlisesGamer, PresentKim]

commands:
    rab:
        usage:        /rab <make | start>
        description:  Main command of RunnersAndBeast